src/main/java/selecao/stefanini/cpg/model/Autor.java
package selecao.stefanini.cpg.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Past;

import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(name = "autor")
public class Autor implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@NotEmpty
	@Column(nullable = false)
	private String nome;

	private String sexo;

	private String email;

	@NotEmpty
	@Temporal(TemporalType.DATE)
	@Past
	@Column(name = "data_nascimento", nullable = false)
	private Date dataNascimento;

	@NotEmpty
	@Column(nullable = false)
	private String pais;

	
	@Column(length = 11)
	private String cpf;


	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getSexo() {
		return sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	public String getPais() {
		return pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

		
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Autor other = (Autor) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Autor [id=" + id + ", nome=" + nome + ", sexo=" + sexo + ", email=" + email + ", dataNascimento="
				+ dataNascimento + ", pais=" + pais + ", cpf=" + cpf + "]";
	}

}

src/main/java/selecao/stefanini/cpg/model/Obra.java
package selecao.stefanini.cpg.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

@Entity
@Table(name = "obra")
public class Obra implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@NotEmpty
	@Column(nullable = false)
	private String nome;
	
	@NotEmpty
	@Column(nullable = false, length = 240)
	private String descricao;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "data_publicacao")
	private Date dataPublicacao;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_exposicao")
	private Date dataExposicao;
	
    @NotNull
    @JoinTable(name="obra_autor")
    @ManyToMany(fetch = FetchType.LAZY)
	private List<Autor> autoresLista;
    
    @Transient
    private Autor autor;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Date getDataPublicacao() {
		return dataPublicacao;
	}

	public void setDataPublicacao(Date dataPublicacao) {
		this.dataPublicacao = dataPublicacao;
	}

	public Date getDataExposicao() {
		return dataExposicao;
	}

	public void setDataExposicao(Date dataExposicao) {
		this.dataExposicao = dataExposicao;
	}
	

	public List<Autor> getAutoresLista() {
		return autoresLista;
	}

	public void setAutoresLista(List<Autor> autoresLista) {
		this.autoresLista = autoresLista;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Obra other = (Obra) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Obra [id=" + id + ", nome=" + nome + ", descricao=" + descricao + ", dataPublicacao=" + dataPublicacao
				+ ", dataExposicao=" + dataExposicao + "]";
	}
	
		
	
}

src/main/java/selecao/stefanini/cpg/controller/GestaoAutoresBean.java
package selecao.stefanini.cpg.controller;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import selecao.stefanini.cpg.model.Autor;
import selecao.stefanini.cpg.repository.Autores;
import selecao.stefanini.cpg.service.CadastroAutorService;
import selecao.stefanini.cpg.util.FacesMessages;

@Named
@ViewScoped
public class GestaoAutoresBean implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @Inject
    private Autores autores;
    
    @Inject
    private FacesMessages messages;
    
    
    @Inject
    private CadastroAutorService cadastroAutorService;
    
    private List<Autor> listaAutores;
    
    private String termoPesquisa;
    
       
    private Autor autor;
    
    public void prepararNovoAutor() {
        autor = new Autor();
    }
    
    
    public void salvar() {
        cadastroAutorService.salvar(autor);
        
        atualizarRegistros();
        
        messages.info("Autor salva com sucesso!");
        
        RequestContext.getCurrentInstance().update(Arrays.asList(
                "frm:autoresDataTable", "frm:messages"));
    }
    
    public void excluir() {
        cadastroAutorService.excluir(autor);
        
        autor = null;
        
        atualizarRegistros();
        
        messages.info("Autor excluída com sucesso!");
    }
    
    public void pesquisar() {
        listaAutores = autores.pesquisar(termoPesquisa);
        
        if (listaAutores.isEmpty()) {
            messages.info("Sua consulta não retornou registros.");
        }
    }
    
    public void todosAutores() {
        listaAutores = autores.todos();
    }
    
    
    private void atualizarRegistros() {
        if (jaHouvePesquisa()) {
            pesquisar();
        } else {
            todosAutores();
        }
    }
    
    private boolean jaHouvePesquisa() {
        return termoPesquisa != null && !"".equals(termoPesquisa);
    }
    
    public List<Autor> getlistaAutores() {
        return listaAutores;
    }
    
    public String getTermoPesquisa() {
        return termoPesquisa;
    }
    
    public void setTermoPesquisa(String termoPesquisa) {
        this.termoPesquisa = termoPesquisa;
    }
    
      
    public Autor getAutor() {
        return autor;
    }
    
    public void setAutor(Autor autor) {
        this.autor = autor;
    }
    
    public boolean isAutorSeleciona() {
        return autor != null && autor.getId() != null;
    }
}

src/main/java/selecao/stefanini/cpg/controller/GestaoObrasBean.java
package selecao.stefanini.cpg.controller;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import selecao.stefanini.cpg.model.Obra;
import selecao.stefanini.cpg.repository.Obras;
import selecao.stefanini.cpg.service.CadastroObraService;
import selecao.stefanini.cpg.util.FacesMessages;

@Named
@ViewScoped
public class GestaoObrasBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private Obras obras;

	@Inject
	private FacesMessages messages;
	
	 @Inject
	 private CadastroObraService cadastroObraService;

	private List<Obra> listaObras;

	private String termoPesquisa;

	private Obra obra;

	public void prepararNovaObra() {
		obra = new Obra();
	}

	public void salvar() {
		cadastroObraService.salvar(obra);

		atualizarRegistros();

		messages.info("Obra salva com sucesso!");

		RequestContext.getCurrentInstance().update(Arrays.asList("frm:obrasDataTable", "frm:messages"));
	}

	public void excluir() {
		cadastroObraService.excluir(obra);

		obra = null;

		atualizarRegistros();

		messages.info("Obra excluída com sucesso!");
	}

	public void pesquisar() {
		listaObras = obras.pesquisar(termoPesquisa);

		if (listaObras.isEmpty()) {
			messages.info("Sua consulta não retornou registros.");
		}
	}

	public void todasObras() {
		listaObras = obras.todas();
	}

	private void atualizarRegistros() {
		if (jaHouvePesquisa()) {
			pesquisar();
		} else {
			todasObras();
		}
	}

	private boolean jaHouvePesquisa() {
		return termoPesquisa != null && !"".equals(termoPesquisa);
	}

	public List<Obra> getListaObras() {
		return listaObras;
	}

	public String getTermoPesquisa() {
		return termoPesquisa;
	}

	public void setTermoPesquisa(String termoPesquisa) {
		this.termoPesquisa = termoPesquisa;
	}
	
    public Obra getObra() {
        return obra;
    }
    
    public void setObra(Obra obra) {
        this.obra = obra;
    }
    
    public boolean isObraSeleciona() {
        return obra != null && obra.getId() != null;
    }

}

src/main/webapp/GestaoAutores.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	template="WEB-INF/template/Layout.xhtml">

	<ui:define name="titulo">
	Cadastros Autores
</ui:define>

	<ui:define name="conteudo">
		<f:metadata>
			<f:viewAction action="#{gestaoAutoresBean.todosAutores}" />
		</f:metadata>

		<h:form id="frm">
			<p:messages id="messages" />

			<p:toolbar id="toolbar" value="Cadastro Autores">
				<f:facet name="left">
					<p:inputText id="termoPesquisa"
						placeholder="Digite aqui um termo para pesquisa..." size="30"
						value="#{gestaoAutoresBean.termoPesquisa}" />

					<p:commandButton value="Pesquisar" icon="fa fa-search"
						actionListener="#{gestaoAutoresBean.pesquisar}"
						update="autoresDataTable messages" process="@this termoPesquisa" />

					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>

					<p:commandButton value="Novo" icon="fa fa-plus"
						actionListener="#{gestaoAutoresBean.prepararNovoAutor}"
						oncomplete="PF('autorDialogWidgetVar').show()"
						update="autorDialog" process="@this">
						<p:resetInput target="autorDialog" />
					</p:commandButton>

					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>

					<p:commandButton value="Editar" title="Editar" icon="fa fa-edit"
						disabled="#{not gestaoAutoresBean.autorSeleciona}"
						oncomplete="PF('autorDialogWidgetVar').show()"
						update="autorDialog" process="@this">
						<p:resetInput target="autorDialog" />
					</p:commandButton>

					<p:commandButton value="Excluir" title="Excluir" icon="fa fa-trash"
						disabled="#{not gestaoAutoresBean.autorSeleciona}"
						actionListener="#{gestaoAutoresBean.excluir}"
						update="messages autoresDataTable toolbar" process="@this" />

					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>


				</f:facet>
			</p:toolbar>

			<p:spacer height="10px" />

			<p:dataTable id="autoresDataTable"
				value="#{gestaoAutoresBean.listaAutores}" var="autor"
				emptyMessage="Nenhuma informação a ser exibida" paginator="true"
				rows="10" paginatorPosition="bottom" selectionMode="single"
				selection="#{gestaoAutoresBean.autor}" rowKey="#{autor.id}">

				<p:ajax event="rowSelect" update="frm:toolbar" />

				<p:ajax event="rowUnselect" update="frm:toolbar" />

				<p:column headerText="Nome" sortBy="#{autor.nome}">
					<h:outputText value="#{autor.nome}" />
				</p:column>

				<p:column headerText="email">
					<h:outputText value="#{autor.email}" />
				</p:column>

				<p:column headerText="Data Nascimento">
					<h:outputText value="#{autor.dataNascimento}" />
				</p:column>

				<p:column headerText="País">
					<h:outputText value="#{autor.pais}" />
				</p:column>
			</p:dataTable>

			<p:dialog id="autorDialog" header="Novo autor"
				widgetVar="autorDialogWidgetVar" modal="true" resizable="false"
				closeOnEscape="true">
				<p:messages id="autorMessages" />

				<p:defaultCommand target="salvarCommandButton" scope="autorDialog" />

				<h:panelGrid id="autorPanelGrid" columns="2"
					rendered="#{gestaoAutoresBean.autor ne null}">
					<p:outputLabel value="Nome: " for="nome" />
					<p:inputText id="nome" size="5" maxlength="120"
						value="#{gestaoAutoresBean.autor.nome}" />

					<p:outputLabel value="Email: " for="email" />
					<p:inputText id="email" size="80" maxlength="80"
						value="#{gestaoAutoresBean.autor.email}" />


					<p:outputLabel value="CPF: " for="cpf" />
					<p:inputMask id="cpf" mask="999.999.999-99" size="11"
						maxlength="11" value="#{gestaoAutoresBean.autor.cpf}" />

					<p:outputLabel value="Data Nascimento: " for="dataNascimento" />
					<p:calendar id="dataNascimento" pattern="dd/MM/yyyy" size="30"
						value="#{gestaoAutoresBean.autor.dataNascimento}" />

					<p:outputLabel value="País: " for="pais" />
					<p:inputText id="pais" size="2" maxlength="30"
						value="#{gestaoAutoresBean.autor.pais}" />

					<p:commandButton id="salvarCommandButton" value="Salvar"
						actionListener="#{gestaoAutoresBean.salvar}"
						update="autorPanelGrid autorMessages"
						oncomplete="if (!args.validationFailed) PF('autorDialogWidgetVar').hide()"
						process="autorDialog" />
				</h:panelGrid>
			</p:dialog>
		</h:form>

		<p:spacer height="40px" />

<ui:define name="tituloObra">
	Cadastros Obras
</ui:define>

		<f:metadata>
			<f:viewAction action="#{gestaoObrasBean.todasObras}" />
		</f:metadata>

		<h:form id="frm">
			<p:messages id="messages" />

			<p:toolbar id="toolbar">
				<f:facet name="left">
					<p:inputText id="termoPesquisa"
						placeholder="Digite aqui um termo para pesquisa..." size="30"
						value="#{gestaoObrasBean.termoPesquisa}" />

					<p:commandButton value="Pesquisar" icon="fa fa-search"
						actionListener="#{gestaoObrasBean.pesquisar}"
						update="obrasDataTable messages" process="@this termoPesquisa" />

					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>

					<p:commandButton value="Novo" icon="fa fa-plus"
						actionListener="#{gestaoObrasBean.prepararNovoAutor}"
						oncomplete="PF('obraDialogWidgetVar').show()" update="obraDialog"
						process="@this">
						<p:resetInput target="obraDialog" />
					</p:commandButton>

					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>

					<p:commandButton value="Editar" title="Editar" icon="fa fa-edit"
						disabled="#{not gestaoObrasBean.obraSeleciona}"
						oncomplete="PF('obraDialogWidgetVar').show()" update="obraDialog"
						process="@this">
						<p:resetInput target="obraDialog" />
					</p:commandButton>

					<p:commandButton value="Excluir" title="Excluir" icon="fa fa-trash"
						disabled="#{not gestaoObrasBean.obraSeleciona}"
						actionListener="#{gestaoObrasBean.excluir}"
						update="messages obrasDataTable toolbar" process="@this" />

					<span class="ui-separator"> <span
						class="ui-icon ui-icon-grip-dotted-vertical" />
					</span>


				</f:facet>
			</p:toolbar>

			<p:spacer height="20px" />

			<p:dataTable id="obrasDataTable"
				value="#{gestaoObrasBean.listaObras}" var="obra"
				emptyMessage="Nenhuma informação a ser exibida" paginator="true"
				rows="10" paginatorPosition="bottom" selectionMode="single"
				selection="#{gestaoObrasBean.obra}" rowKey="#{obra.id}">

				<p:ajax event="rowSelect" update="frm:toolbar" />

				<p:ajax event="rowUnselect" update="frm:toolbar" />

				<p:column headerText="Nome Obra" sortBy="#{obra.nome}">
					<h:outputText value="#{obra.nome}" />
				</p:column>

				<p:column headerText="Descricao Obra">
					<h:outputText value="#{obra.descricao}" />
				</p:column>

				<p:column headerText="Data Publicacao">
					<h:outputText value="#{obra.dataPublicacao}" />
				</p:column>

				<p:column headerText="Data Exposicao">
					<h:outputText value="#{obra.dataExposicao}" />
				</p:column>
			</p:dataTable>

			<p:dialog id="obraDialog" header="Nova obra"
				widgetVar="obraDialogWidgetVar" modal="true" resizable="false"
				closeOnEscape="true">
				<p:messages id="obraMessages" />

				<p:defaultCommand target="salvarCommandButton" scope="obraDialog" />

				<h:panelGrid id="obraPanelGrid" columns="2"
					rendered="#{gestaoObrasBean.obra ne null}">
					<p:outputLabel value="Nome: " for="nome" />
					<p:inputText id="nome" size="5" maxlength="120"
						value="#{gestaoObrasBean.obra.nome}" />

					<p:outputLabel value="Descricao: " for="descricao" />
					<p:inputText id="descricao" size="10" maxlength="240"
						value="#{gestaoObrasBean.obra.descricao}" />



					<p:outputLabel value="Data Publicacao: " for="dataPublicacao" />
					<p:calendar id="dataPublicacao" pattern="dd/MM/yyyy" size="30"
						value="#{gestaoObrasBean.obra.dataPublicacao}" />

					<p:outputLabel value="Data Exposicao: " for="dataExposicao" />
					<p:calendar id="dataExposicao" pattern="dd/MM/yyyy" size="30"
						value="#{gestaoObrasBean.obra.dataExposicao}" />



					<p:commandButton id="salvarCommandButton" value="Salvar"
						actionListener="#{gestaoObrasBean.salvar}"
						update="obraPanelGrid obraMessages"
						oncomplete="if (!args.validationFailed) PF('obraDialogWidgetVar').hide()"
						process="obraDialog" />
				</h:panelGrid>
			</p:dialog>
		</h:form>

	</ui:define>

</ui:composition>